BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "words" (
	"id"	INTEGER NOT NULL,
	"korean_word"	TEXT NOT NULL,
	"romanization"	TEXT NOT NULL,
	"indonesian_translation"	TEXT NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);
INSERT INTO "words" VALUES (1,'안녕하세요','Annyeonghaseyo','Halo / Apa kabar');
INSERT INTO "words" VALUES (2,'감사합니다','Gamsahamnida','Terima kasih (formal)');
INSERT INTO "words" VALUES (3,'고맙습니다','Gomapseumnida','Terima kasih (formal)');
INSERT INTO "words" VALUES (4,'네','Ne','Ya');
INSERT INTO "words" VALUES (5,'아니요','Aniyo','Tidak / Bukan');
INSERT INTO "words" VALUES (6,'죄송합니다','Joesonghamnida','Maaf (formal)');
INSERT INTO "words" VALUES (7,'미안합니다','Mianhamnida','Maaf (formal)');
INSERT INTO "words" VALUES (8,'괜찮아요','Gwaenchanayo','Tidak apa-apa');
INSERT INTO "words" VALUES (9,'주세요','Juseyo','Tolong beri saya');
INSERT INTO "words" VALUES (10,'이름이 뭐예요?','Ireumi mwoyeyo?','Siapa nama Anda?');
INSERT INTO "words" VALUES (11,'제 이름은 ...입니다','Je ireumeun ...imnida','Nama saya adalah ...');
INSERT INTO "words" VALUES (12,'만나서 반갑습니다','Mannaseo bangapseumnida','Senang bertemu dengan Anda');
INSERT INTO "words" VALUES (13,'안녕히 가세요','Annyeonghi gaseyo','Selamat jalan (kepada yang pergi)');
INSERT INTO "words" VALUES (14,'안녕히 계세요','Annyeonghi gyeseyo','Selamat tinggal (kepada yang tinggal)');
INSERT INTO "words" VALUES (15,'잘 먹겠습니다','Jal meokgesseumnida','Selamat makan (sebelum makan)');
INSERT INTO "words" VALUES (16,'잘 먹었습니다','Jal meogeosseumnida','Terima kasih atas makanannya (setelah makan)');
INSERT INTO "words" VALUES (17,'사랑해요','Saranghaeyo','Aku cinta kamu');
INSERT INTO "words" VALUES (18,'도와주세요','Dowajuseyo','Tolong bantu saya');
INSERT INTO "words" VALUES (19,'이것','Igeot','Ini');
INSERT INTO "words" VALUES (20,'저것','Jeogeot','Itu (jauh)');
INSERT INTO "words" VALUES (21,'그것','Geugeot','Itu (dekat lawan bicara)');
INSERT INTO "words" VALUES (22,'일','Il','Satu (Sino-Korea)');
INSERT INTO "words" VALUES (23,'이','I','Dua (Sino-Korea)');
INSERT INTO "words" VALUES (24,'삼','Sam','Tiga (Sino-Korea)');
INSERT INTO "words" VALUES (25,'사','Sa','Empat (Sino-Korea)');
INSERT INTO "words" VALUES (26,'오','O','Lima (Sino-Korea)');
INSERT INTO "words" VALUES (27,'육','Yuk','Enam (Sino-Korea)');
INSERT INTO "words" VALUES (28,'칠','Chil','Tujuh (Sino-Korea)');
INSERT INTO "words" VALUES (29,'팔','Pal','Delapan (Sino-Korea)');
INSERT INTO "words" VALUES (30,'구','Gu','Sembilan (Sino-Korea)');
INSERT INTO "words" VALUES (31,'십','Sip','Sepuluh (Sino-Korea)');
INSERT INTO "words" VALUES (32,'하나','Hana','Satu (Asli Korea)');
INSERT INTO "words" VALUES (33,'둘','Dul','Dua (Asli Korea)');
INSERT INTO "words" VALUES (34,'셋','Set','Tiga (Asli Korea)');
INSERT INTO "words" VALUES (35,'넷','Net','Empat (Asli Korea)');
INSERT INTO "words" VALUES (36,'다섯','Daseot','Lima (Asli Korea)');
INSERT INTO "words" VALUES (37,'여섯','Yeoseot','Enam (Asli Korea)');
INSERT INTO "words" VALUES (38,'일곱','Ilgop','Tujuh (Asli Korea)');
INSERT INTO "words" VALUES (39,'여덟','Yeodeol','Delapan (Asli Korea)');
INSERT INTO "words" VALUES (40,'아홉','Ahop','Sembilan (Asli Korea)');
INSERT INTO "words" VALUES (41,'열','Yeol','Sepuluh (Asli Korea)');
INSERT INTO "words" VALUES (42,'오늘','Oneul','Hari ini');
INSERT INTO "words" VALUES (43,'어제','Eoje','Kemarin');
INSERT INTO "words" VALUES (44,'내일','Naeil','Besok');
INSERT INTO "words" VALUES (45,'지금','Jigeum','Sekarang');
INSERT INTO "words" VALUES (46,'아침','Achim','Pagi');
INSERT INTO "words" VALUES (47,'점심','Jeomsim','Siang');
INSERT INTO "words" VALUES (48,'저녁','Jeonyeok','Malam');
INSERT INTO "words" VALUES (49,'시간','Sigan','Waktu / Jam');
INSERT INTO "words" VALUES (50,'분','Bun','Menit');
INSERT INTO "words" VALUES (51,'초','Cho','Detik');
INSERT INTO "words" VALUES (52,'월요일','Woryoil','Senin');
INSERT INTO "words" VALUES (53,'화요일','Hwayoil','Selasa');
INSERT INTO "words" VALUES (54,'수요일','Suyoil','Rabu');
INSERT INTO "words" VALUES (55,'목요일','Mogyoil','Kamis');
INSERT INTO "words" VALUES (56,'금요일','Geumyoil','Jumat');
INSERT INTO "words" VALUES (57,'토요일','Toyoil','Sabtu');
INSERT INTO "words" VALUES (58,'일요일','Iryoil','Minggu');
INSERT INTO "words" VALUES (59,'주말','Jumal','Akhir pekan');
INSERT INTO "words" VALUES (60,'년','Nyeon','Tahun');
INSERT INTO "words" VALUES (61,'월','Wol','Bulan');
INSERT INTO "words" VALUES (62,'일','Il','Hari (tanggal)');
INSERT INTO "words" VALUES (63,'사람','Saram','Orang');
INSERT INTO "words" VALUES (64,'남자','Namja','Laki-laki');
INSERT INTO "words" VALUES (65,'여자','Yeoja','Perempuan');
INSERT INTO "words" VALUES (66,'아이','Ai','Anak');
INSERT INTO "words" VALUES (67,'친구','Chingu','Teman');
INSERT INTO "words" VALUES (68,'가족','Gajok','Keluarga');
INSERT INTO "words" VALUES (69,'아버지','Abeoji','Ayah');
INSERT INTO "words" VALUES (70,'어머니','Eomeoni','Ibu');
INSERT INTO "words" VALUES (71,'형','Hyeong','Kakak laki-laki (untuk laki-laki)');
INSERT INTO "words" VALUES (72,'오빠','Oppa','Kakak laki-laki (untuk perempuan)');
INSERT INTO "words" VALUES (73,'누나','Nuna','Kakak perempuan (untuk laki-laki)');
INSERT INTO "words" VALUES (74,'언니','Eonni','Kakak perempuan (untuk perempuan)');
INSERT INTO "words" VALUES (75,'동생','Dongsaeng','Adik');
INSERT INTO "words" VALUES (76,'남편','Nampyeon','Suami');
INSERT INTO "words" VALUES (77,'아내','Anae','Istri');
INSERT INTO "words" VALUES (78,'할아버지','Harabeoji','Kakek');
INSERT INTO "words" VALUES (79,'할머니','Halmeoni','Nenek');
INSERT INTO "words" VALUES (80,'선생님','Seonsaengnim','Guru');
INSERT INTO "words" VALUES (81,'학생','Haksaeng','Siswa');
INSERT INTO "words" VALUES (82,'의사','Uisa','Dokter');
INSERT INTO "words" VALUES (83,'회사원','Hoesawon','Pegawai kantoran');
INSERT INTO "words" VALUES (84,'집','Jip','Rumah');
INSERT INTO "words" VALUES (85,'학교','Hakgyo','Sekolah');
INSERT INTO "words" VALUES (86,'병원','Byeongwon','Rumah sakit');
INSERT INTO "words" VALUES (87,'가게','Gage','Toko');
INSERT INTO "words" VALUES (88,'시장','Sijang','Pasar');
INSERT INTO "words" VALUES (89,'회사','Hoesa','Perusahaan');
INSERT INTO "words" VALUES (90,'식당','Sikdang','Restoran');
INSERT INTO "words" VALUES (91,'은행','Eunhaeng','Bank');
INSERT INTO "words" VALUES (92,'공항','Gonghang','Bandara');
INSERT INTO "words" VALUES (93,'지하철','Jihacheol','Kereta bawah tanah');
INSERT INTO "words" VALUES (94,'역','Yeok','Stasiun');
INSERT INTO "words" VALUES (95,'화장실','Hwajangsil','Toilet');
INSERT INTO "words" VALUES (96,'한국','Hanguk','Korea Selatan');
INSERT INTO "words" VALUES (97,'서울','Seoul','Seoul');
INSERT INTO "words" VALUES (98,'공원','Gongwon','Taman');
INSERT INTO "words" VALUES (99,'도서관','Doseogwan','Perpustakaan');
INSERT INTO "words" VALUES (100,'약국','Yakguk','Apotek');
INSERT INTO "words" VALUES (101,'우체국','Ucheguk','Kantor pos');
INSERT INTO "words" VALUES (102,'교실','Gyosil','Ruang kelas');
INSERT INTO "words" VALUES (103,'방','Bang','Kamar');
INSERT INTO "words" VALUES (104,'음식','Eumsik','Makanan');
INSERT INTO "words" VALUES (105,'물','Mul','Air');
INSERT INTO "words" VALUES (106,'밥','Bap','Nasi');
INSERT INTO "words" VALUES (107,'빵','Ppang','Roti');
INSERT INTO "words" VALUES (108,'고기','Gogi','Daging');
INSERT INTO "words" VALUES (109,'생선','Saengseon','Ikan');
INSERT INTO "words" VALUES (110,'채소','Chaeso','Sayuran');
INSERT INTO "words" VALUES (111,'과일','Gwail','Buah');
INSERT INTO "words" VALUES (112,'커피','Keopi','Kopi');
INSERT INTO "words" VALUES (113,'차','Cha','Teh');
INSERT INTO "words" VALUES (114,'우유','Uyu','Susu');
INSERT INTO "words" VALUES (115,'주스','Juseu','Jus');
INSERT INTO "words" VALUES (116,'김치','Gimchi','Kimchi');
INSERT INTO "words" VALUES (117,'불고기','Bulgogi','Bulgogi');
INSERT INTO "words" VALUES (118,'비빔밥','Bibimbap','Bibimbap');
INSERT INTO "words" VALUES (119,'라면','Ramyeon','Ramen');
INSERT INTO "words" VALUES (120,'사과','Sagwa','Apel');
INSERT INTO "words" VALUES (121,'바나나','Banana','Pisang');
INSERT INTO "words" VALUES (122,'딸기','Ttalgi','Stroberi');
INSERT INTO "words" VALUES (123,'오렌지','Orenji','Jeruk');
INSERT INTO "words" VALUES (124,'책','Chaek','Buku');
INSERT INTO "words" VALUES (125,'돈','Don','Uang');
INSERT INTO "words" VALUES (126,'전화','Jeonhwa','Telepon');
INSERT INTO "words" VALUES (127,'컴퓨터','Keompyuteo','Komputer');
INSERT INTO "words" VALUES (128,'텔레비전','Tellebijeon','Televisi');
INSERT INTO "words" VALUES (129,'의자','Uija','Kursi');
INSERT INTO "words" VALUES (130,'책상','Chaeksang','Meja');
INSERT INTO "words" VALUES (131,'문','Mun','Pintu');
INSERT INTO "words" VALUES (132,'창문','Changmun','Jendela');
INSERT INTO "words" VALUES (133,'침대','Chimdae','Tempat tidur');
INSERT INTO "words" VALUES (134,'옷','Ot','Pakaian');
INSERT INTO "words" VALUES (135,'신발','Sinbal','Sepatu');
INSERT INTO "words" VALUES (136,'가방','Gabang','Tas');
INSERT INTO "words" VALUES (137,'모자','Moja','Topi');
INSERT INTO "words" VALUES (138,'안경','An-gyeong','Kacamata');
INSERT INTO "words" VALUES (139,'사진','Sajin','Foto');
INSERT INTO "words" VALUES (140,'지도','Jido','Peta');
INSERT INTO "words" VALUES (141,'펜','Pen','Pena');
INSERT INTO "words" VALUES (142,'공책','Gongchaek','Buku tulis');
INSERT INTO "words" VALUES (143,'시계','Sigye','Jam');
INSERT INTO "words" VALUES (144,'가다','Gada','Pergi');
INSERT INTO "words" VALUES (145,'오다','Oda','Datang');
INSERT INTO "words" VALUES (146,'먹다','Meokda','Makan');
INSERT INTO "words" VALUES (147,'마시다','Masida','Minum');
INSERT INTO "words" VALUES (148,'자다','Jada','Tidur');
INSERT INTO "words" VALUES (149,'보다','Boda','Melihat / Menonton');
INSERT INTO "words" VALUES (150,'듣다','Deutda','Mendengar');
INSERT INTO "words" VALUES (151,'읽다','Ikda','Membaca');
INSERT INTO "words" VALUES (152,'쓰다','Sseuda','Menulis / Menggunakan');
INSERT INTO "words" VALUES (153,'말하다','Malhada','Berbicara');
INSERT INTO "words" VALUES (154,'하다','Hada','Melakukan');
INSERT INTO "words" VALUES (155,'사다','Sada','Membeli');
INSERT INTO "words" VALUES (156,'팔다','Palda','Menjual');
INSERT INTO "words" VALUES (157,'알다','Alda','Tahu');
INSERT INTO "words" VALUES (158,'모르다','Moreuda','Tidak tahu');
INSERT INTO "words" VALUES (159,'좋아하다','Joahada','Suka');
INSERT INTO "words" VALUES (160,'싫어하다','Sireohada','Tidak suka');
INSERT INTO "words" VALUES (161,'배우다','Baeuda','Belajar');
INSERT INTO "words" VALUES (162,'가르치다','Gareuchida','Mengajar');
INSERT INTO "words" VALUES (163,'일하다','Ilhada','Bekerja');
INSERT INTO "words" VALUES (164,'쉬다','Swida','Beristirahat');
INSERT INTO "words" VALUES (165,'만나다','Mannada','Bertemu');
INSERT INTO "words" VALUES (166,'기다리다','Gidarida','Menunggu');
INSERT INTO "words" VALUES (167,'주다','Juda','Memberi');
INSERT INTO "words" VALUES (168,'받다','Batda','Menerima');
INSERT INTO "words" VALUES (169,'열다','Yeolda','Membuka');
INSERT INTO "words" VALUES (170,'닫다','Datda','Menutup');
INSERT INTO "words" VALUES (171,'살다','Salda','Tinggal / Hidup');
INSERT INTO "words" VALUES (172,'죽다','Jukda','Mati');
INSERT INTO "words" VALUES (173,'웃다','Utda','Tertawa');
INSERT INTO "words" VALUES (174,'울다','Ulda','Menangis');
INSERT INTO "words" VALUES (175,'입다','Ipda','Memakai (pakaian)');
INSERT INTO "words" VALUES (176,'벗다','Beotda','Melepas (pakaian)');
INSERT INTO "words" VALUES (177,'타다','Tada','Naik (kendaraan)');
INSERT INTO "words" VALUES (178,'내리다','Naerida','Turun (kendaraan)');
INSERT INTO "words" VALUES (179,'걷다','Geotda','Berjalan');
INSERT INTO "words" VALUES (180,'뛰다','Ttwida','Berlari');
INSERT INTO "words" VALUES (181,'만들다','Mandeulda','Membuat');
INSERT INTO "words" VALUES (182,'운동하다','Undonghada','Berolahraga');
INSERT INTO "words" VALUES (183,'공부하다','Gongbuhada','Belajar');
INSERT INTO "words" VALUES (184,'사랑하다','Saranghada','Mencintai');
INSERT INTO "words" VALUES (185,'전화하다','Jeonhwahada','Menelepon');
INSERT INTO "words" VALUES (186,'요리하다','Yorihada','Memasak');
INSERT INTO "words" VALUES (187,'청소하다','Cheongsohada','Membersihkan');
INSERT INTO "words" VALUES (188,'노래하다','Noraehada','Menyanyi');
INSERT INTO "words" VALUES (189,'춤추다','Chumchuda','Menari');
INSERT INTO "words" VALUES (190,'도착하다','Dochakada','Tiba');
INSERT INTO "words" VALUES (191,'출발하다','Chulbalhada','Berangkat');
INSERT INTO "words" VALUES (192,'앉다','Antda','Duduk');
INSERT INTO "words" VALUES (193,'서다','Seoda','Berdiri');
INSERT INTO "words" VALUES (194,'있다','Itda','Ada / Punya');
INSERT INTO "words" VALUES (195,'없다','Eopda','Tidak ada / Tidak punya');
INSERT INTO "words" VALUES (196,'찍다','Jjikda','Mengambil (foto)');
INSERT INTO "words" VALUES (197,'보내다','Bonaeda','Mengirim');
INSERT INTO "words" VALUES (198,'찾다','Chatda','Mencari');
INSERT INTO "words" VALUES (199,'생각하다','Saenggakada','Berpikir');
INSERT INTO "words" VALUES (200,'묻다','Mutda','Bertanya');
INSERT INTO "words" VALUES (201,'대답하다','Daedapada','Menjawab');
INSERT INTO "words" VALUES (202,'믿다','Mitda','Percaya');
INSERT INTO "words" VALUES (203,'도와주다','Dowajuda','Membantu');
INSERT INTO "words" VALUES (204,'잊다','Itda','Lupa');
INSERT INTO "words" VALUES (205,'기억하다','Gieokada','Ingat');
INSERT INTO "words" VALUES (206,'시작하다','Sijakada','Memulai');
INSERT INTO "words" VALUES (207,'끝나다','Kkeunnada','Selesai');
INSERT INTO "words" VALUES (208,'크다','Keuda','Besar');
INSERT INTO "words" VALUES (209,'작다','Jakda','Kecil');
INSERT INTO "words" VALUES (210,'많다','Manta','Banyak');
INSERT INTO "words" VALUES (211,'적다','Jeokda','Sedikit');
INSERT INTO "words" VALUES (212,'좋다','Jota','Bagus / Baik');
INSERT INTO "words" VALUES (213,'나쁘다','Nappeuda','Buruk / Jelek');
INSERT INTO "words" VALUES (214,'재미있다','Jaemi-itda','Menarik / Seru');
INSERT INTO "words" VALUES (215,'재미없다','Jaemi-eopda','Tidak menarik / Membosankan');
INSERT INTO "words" VALUES (216,'맛있다','Masitda','Enak');
INSERT INTO "words" VALUES (217,'맛없다','Madeopda','Tidak enak');
INSERT INTO "words" VALUES (218,'덥다','Deopda','Panas (cuaca)');
INSERT INTO "words" VALUES (219,'춥다','Chupda','Dingin (cuaca)');
INSERT INTO "words" VALUES (220,'뜨겁다','Tteugeopda','Panas (benda)');
INSERT INTO "words" VALUES (221,'차갑다','Chagapda','Dingin (benda)');
INSERT INTO "words" VALUES (222,'쉽다','Swipda','Mudah');
INSERT INTO "words" VALUES (223,'어렵다','Eoryeopda','Sulit');
INSERT INTO "words" VALUES (224,'비싸다','Bissada','Mahal');
INSERT INTO "words" VALUES (225,'싸다','Ssada','Murah');
INSERT INTO "words" VALUES (226,'예쁘다','Yeppeuda','Cantik');
INSERT INTO "words" VALUES (227,'아름답다','Areumdapda','Indah');
INSERT INTO "words" VALUES (228,'귀엽다','Gwiyeopda','Imut');
INSERT INTO "words" VALUES (229,'멋있다','Meositda','Keren');
INSERT INTO "words" VALUES (230,'착하다','Chakada','Baik hati');
INSERT INTO "words" VALUES (231,'똑똑하다','Ttokttokada','Pintar');
INSERT INTO "words" VALUES (232,'바쁘다','Bappeuda','Sibuk');
INSERT INTO "words" VALUES (233,'피곤하다','Pigonhada','Lelah');
INSERT INTO "words" VALUES (234,'아프다','Apeuda','Sakit');
INSERT INTO "words" VALUES (235,'기쁘다','Gippeuda','Senang');
INSERT INTO "words" VALUES (236,'슬프다','Seulpeuda','Sedih');
INSERT INTO "words" VALUES (237,'행복하다','Haengbokada','Bahagia');
INSERT INTO "words" VALUES (238,'새롭다','Saeropda','Baru');
INSERT INTO "words" VALUES (239,'깨끗하다','Kkaekkeuthada','Bersih');
INSERT INTO "words" VALUES (240,'더럽다','Deoreopda','Kotor');
INSERT INTO "words" VALUES (241,'가깝다','Gakkapda','Dekat');
INSERT INTO "words" VALUES (242,'멀다','Meolda','Jauh');
INSERT INTO "words" VALUES (243,'빠르다','Ppareuda','Cepat');
INSERT INTO "words" VALUES (244,'느리다','Neurida','Lambat');
INSERT INTO "words" VALUES (245,'높다','Nopda','Tinggi');
INSERT INTO "words" VALUES (246,'낮다','Natda','Rendah');
INSERT INTO "words" VALUES (247,'길다','Gilda','Panjang');
INSERT INTO "words" VALUES (248,'짧다','Jjalda','Pendek');
INSERT INTO "words" VALUES (249,'같다','Gatda','Sama');
INSERT INTO "words" VALUES (250,'다르다','Dareuda','Berbeda');
INSERT INTO "words" VALUES (251,'무겁다','Mugeopda','Berat');
INSERT INTO "words" VALUES (252,'가볍다','Gabyeopda','Ringan');
INSERT INTO "words" VALUES (253,'조용하다','Joyonghada','Tenang / Sunyi');
INSERT INTO "words" VALUES (254,'시끄럽다','Sikkeureopda','Berisik');
INSERT INTO "words" VALUES (255,'아주','Aju','Sangat');
INSERT INTO "words" VALUES (256,'너무','Neomu','Terlalu / Sangat');
INSERT INTO "words" VALUES (257,'정말','Jeongmal','Sungguh / Benar-benar');
INSERT INTO "words" VALUES (258,'진짜','Jinjja','Sungguh / Asli');
INSERT INTO "words" VALUES (259,'같이','Gachi','Bersama');
INSERT INTO "words" VALUES (260,'혼자','Honja','Sendiri');
INSERT INTO "words" VALUES (261,'그리고','Geurigo','Dan / Lalu');
INSERT INTO "words" VALUES (262,'그러나','Geureona','Tetapi');
INSERT INTO "words" VALUES (263,'그래서','Geuraeseo','Jadi / Oleh karena itu');
INSERT INTO "words" VALUES (264,'하지만','Hajiman','Tetapi / Namun');
INSERT INTO "words" VALUES (265,'왜','Wae','Kenapa');
INSERT INTO "words" VALUES (266,'언제','Eonje','Kapan');
INSERT INTO "words" VALUES (267,'어디','Eodi','Di mana');
INSERT INTO "words" VALUES (268,'누가','Nuga','Siapa');
INSERT INTO "words" VALUES (269,'무엇','Mueot','Apa');
INSERT INTO "words" VALUES (270,'어떻게','Eotteoke','Bagaimana');
INSERT INTO "words" VALUES (271,'얼마나','Eolmana','Berapa banyak / Berapa lama');
INSERT INTO "words" VALUES (272,'여기','Yeogi','Di sini');
INSERT INTO "words" VALUES (273,'저기','Jeogi','Di sana');
INSERT INTO "words" VALUES (274,'거기','Geogi','Di situ');
INSERT INTO "words" VALUES (275,'위','Wi','Atas');
INSERT INTO "words" VALUES (276,'아래','Arae','Bawah');
INSERT INTO "words" VALUES (277,'앞','Ap','Depan');
INSERT INTO "words" VALUES (278,'뒤','Dwi','Belakang');
INSERT INTO "words" VALUES (279,'안','An','Dalam');
INSERT INTO "words" VALUES (280,'밖','Bak','Luar');
INSERT INTO "words" VALUES (281,'옆','Yeop','Samping');
INSERT INTO "words" VALUES (282,'동물','Dongmul','Hewan');
INSERT INTO "words" VALUES (283,'개','Gae','Anjing');
INSERT INTO "words" VALUES (284,'고양이','Goyangi','Kucing');
INSERT INTO "words" VALUES (285,'새','Sae','Burung');
INSERT INTO "words" VALUES (286,'물고기','Mul-gogi','Ikan');
INSERT INTO "words" VALUES (287,'호랑이','Horangi','Harimau');
INSERT INTO "words" VALUES (288,'사자','Saja','Singa');
INSERT INTO "words" VALUES (289,'코끼리','Kokkiri','Gajah');
INSERT INTO "words" VALUES (290,'원숭이','Wonsungi','Monyet');
INSERT INTO "words" VALUES (291,'소','So','Sapi');
INSERT INTO "words" VALUES (292,'돼지','Dwaeji','Babi');
INSERT INTO "words" VALUES (293,'날씨','Nalssi','Cuaca');
INSERT INTO "words" VALUES (294,'봄','Bom','Musim semi');
INSERT INTO "words" VALUES (295,'여름','Yeoreum','Musim panas');
INSERT INTO "words" VALUES (296,'가을','Gaeul','Musim gugur');
INSERT INTO "words" VALUES (297,'겨울','Gyeoul','Musim dingin');
INSERT INTO "words" VALUES (298,'해','Hae','Matahari');
INSERT INTO "words" VALUES (299,'달','Dal','Bulan');
INSERT INTO "words" VALUES (300,'별','Byeol','Bintang');
INSERT INTO "words" VALUES (301,'하늘','Haneul','Langit');
INSERT INTO "words" VALUES (302,'구름','Gureum','Awan');
INSERT INTO "words" VALUES (303,'비','Bi','Hujan');
INSERT INTO "words" VALUES (304,'눈','Nun','Salju / Mata');
INSERT INTO "words" VALUES (305,'바람','Baram','Angin');
INSERT INTO "words" VALUES (306,'강','Gang','Sungai');
INSERT INTO "words" VALUES (307,'바다','Bada','Laut');
INSERT INTO "words" VALUES (308,'산','San','Gunung');
INSERT INTO "words" VALUES (309,'나무','Namu','Pohon');
INSERT INTO "words" VALUES (310,'꽃','Kkot','Bunga');
INSERT INTO "words" VALUES (311,'땅','Ttang','Tanah');
INSERT INTO "words" VALUES (312,'불','Bul','Api');
INSERT INTO "words" VALUES (313,'색깔','Saekkkal','Warna');
INSERT INTO "words" VALUES (314,'빨간색','Ppalgansaek','Merah');
INSERT INTO "words" VALUES (315,'주황색','Juhwangsaek','Oranye');
INSERT INTO "words" VALUES (316,'노란색','Noransaek','Kuning');
INSERT INTO "words" VALUES (317,'초록색','Choroksaek','Hijau');
INSERT INTO "words" VALUES (318,'파란색','Paransaek','Biru');
INSERT INTO "words" VALUES (319,'남색','Namsaek','Nila');
INSERT INTO "words" VALUES (320,'보라색','Borasaek','Ungu');
INSERT INTO "words" VALUES (321,'하얀색','Hayansaek','Putih');
INSERT INTO "words" VALUES (322,'검은색','Geomeunsaek','Hitam');
INSERT INTO "words" VALUES (323,'회색','Hoesaek','Abu-abu');
INSERT INTO "words" VALUES (324,'자동차','Jadongcha','Mobil');
INSERT INTO "words" VALUES (325,'버스','Beoseu','Bus');
INSERT INTO "words" VALUES (326,'택시','Taeksi','Taksi');
INSERT INTO "words" VALUES (327,'비행기','Bihaenggi','Pesawat');
INSERT INTO "words" VALUES (328,'자전거','Jajeon-geo','Sepeda');
INSERT INTO "words" VALUES (329,'배','Bae','Kapal / Perut');
INSERT INTO "words" VALUES (330,'기차','Gicha','Kereta api');
INSERT INTO "words" VALUES (331,'몸','Mom','Tubuh');
INSERT INTO "words" VALUES (332,'머리','Meori','Kepala');
INSERT INTO "words" VALUES (333,'얼굴','Eolgul','Wajah');
INSERT INTO "words" VALUES (334,'입','Ip','Mulut');
INSERT INTO "words" VALUES (335,'코','Ko','Hidung');
INSERT INTO "words" VALUES (336,'귀','Gwi','Telinga');
INSERT INTO "words" VALUES (337,'손','Son','Tangan');
INSERT INTO "words" VALUES (338,'발','Bal','Kaki');
INSERT INTO "words" VALUES (339,'다리','Dari','Kaki (seluruh)');
INSERT INTO "words" VALUES (340,'팔','Pal','Lengan');
INSERT INTO "words" VALUES (341,'마음','Maeum','Hati / Pikiran');
INSERT INTO "words" VALUES (342,'취미','Chwimi','Hobi');
INSERT INTO "words" VALUES (343,'영화','Yeonghwa','Film');
INSERT INTO "words" VALUES (344,'음악','Eumak','Musik');
INSERT INTO "words" VALUES (345,'운동','Undong','Olahraga');
INSERT INTO "words" VALUES (346,'여행','Yeohaeng','Perjalanan');
INSERT INTO "words" VALUES (347,'게임','Geim','Permainan');
INSERT INTO "words" VALUES (348,'요리','Yori','Masakan');
INSERT INTO "words" VALUES (349,'그림','Geurim','Gambar');
INSERT INTO "words" VALUES (350,'쇼핑','Syoping','Belanja');
INSERT INTO "words" VALUES (351,'어떤','Eotteon','Yang mana / Seperti apa');
INSERT INTO "words" VALUES (352,'몇','Myeot','Berapa (jumlah)');
INSERT INTO "words" VALUES (353,'무슨','Museun','Apa (jenis)');
INSERT INTO "words" VALUES (354,'누구','Nugu','Siapa');
INSERT INTO "words" VALUES (355,'언제나','Eonjena','Selalu');
INSERT INTO "words" VALUES (356,'가끔','Gakkeum','Kadang-kadang');
INSERT INTO "words" VALUES (357,'자주','Jaju','Sering');
INSERT INTO "words" VALUES (358,'보통','Botong','Biasanya');
INSERT INTO "words" VALUES (359,'나라','Nara','Negara');
INSERT INTO "words" VALUES (360,'도시','Dosi','Kota');
INSERT INTO "words" VALUES (361,'언어','Eoneo','Bahasa');
INSERT INTO "words" VALUES (362,'질문','Jilmun','Pertanyaan');
INSERT INTO "words" VALUES (363,'문제','Munje','Masalah / Soal');
INSERT INTO "words" VALUES (364,'답','Dap','Jawaban');
INSERT INTO "words" VALUES (365,'이유','Iyu','Alasan');
INSERT INTO "words" VALUES (366,'방법','Bangbeop','Cara / Metode');
INSERT INTO "words" VALUES (367,'의미','Uimi','Arti / Makna');
INSERT INTO "words" VALUES (368,'느낌','Neukkim','Perasaan');
INSERT INTO "words" VALUES (369,'생각','Saenggak','Pikiran / Ide');
INSERT INTO "words" VALUES (370,'꿈','Kkum','Mimpi');
INSERT INTO "words" VALUES (371,'목소리','Moksori','Suara');
INSERT INTO "words" VALUES (372,'냄새','Naemsae','Bau');
INSERT INTO "words" VALUES (373,'맛','Mat','Rasa');
INSERT INTO "words" VALUES (374,'소리','Sori','Bunyi');
INSERT INTO "words" VALUES (375,'세상','Sesang','Dunia');
INSERT INTO "words" VALUES (376,'삶','Salm','Kehidupan');
INSERT INTO "words" VALUES (377,'사랑','Sarang','Cinta');
INSERT INTO "words" VALUES (378,'희망','Huimang','Harapan');
INSERT INTO "words" VALUES (379,'약속','Yaksok','Janji');
INSERT INTO "words" VALUES (380,'비밀','Bimil','Rahasia');
INSERT INTO "words" VALUES (381,'선물','Seonmul','Hadiah');
INSERT INTO "words" VALUES (382,'편지','Pyeonji','Surat');
INSERT INTO "words" VALUES (383,'일기','Ilgi','Buku harian');
INSERT INTO "words" VALUES (384,'뉴스','Nyuseu','Berita');
INSERT INTO "words" VALUES (385,'날','Nal','Hari');
INSERT INTO "words" VALUES (386,'밤','Bam','Malam (waktu tidur)');
INSERT INTO "words" VALUES (387,'낮','Nat','Siang hari');
INSERT INTO "words" VALUES (388,'곳','Got','Tempat');
INSERT INTO "words" VALUES (389,'길','Gil','Jalan');
INSERT INTO "words" VALUES (390,'왼쪽','Oenjjok','Kiri');
INSERT INTO "words" VALUES (391,'오른쪽','Oreunjjok','Kanan');
INSERT INTO "words" VALUES (392,'안쪽','Anjjok','Bagian dalam');
INSERT INTO "words" VALUES (393,'바깥쪽','Bakkajjok','Bagian luar');
INSERT INTO "words" VALUES (394,'세','Se','Usia (tahun)');
INSERT INTO "words" VALUES (395,'번','Beon','Kali (hitungan)');
INSERT INTO "words" VALUES (396,'개','Gae','Buah (satuan benda)');
INSERT INTO "words" VALUES (397,'명','Myeong','Orang (satuan hitung)');
INSERT INTO "words" VALUES (398,'병','Byeong','Botol (satuan)');
INSERT INTO "words" VALUES (399,'잔','Jan','Cangkir / Gelas (satuan)');
INSERT INTO "words" VALUES (400,'층','Cheung','Lantai (bangunan)');
INSERT INTO "words" VALUES (401,'물건','Mulgeon','Barang');
INSERT INTO "words" VALUES (402,'가격','Gagyeok','Harga');
INSERT INTO "words" VALUES (403,'번호','Beonho','Nomor');
INSERT INTO "words" VALUES (404,'주소','Juso','Alamat');
INSERT INTO "words" VALUES (405,'직업','Jigeop','Pekerjaan');
INSERT INTO "words" VALUES (406,'수업','Sueop','Pelajaran / Kelas');
INSERT INTO "words" VALUES (407,'시험','Siheom','Ujian');
INSERT INTO "words" VALUES (408,'숙제','Sukje','Pekerjaan rumah');
INSERT INTO "words" VALUES (409,'방학','Banghak','Liburan sekolah');
INSERT INTO "words" VALUES (410,'휴가','Hyuga','Cuti / Liburan');
INSERT INTO "words" VALUES (411,'결혼','Gyeolhon','Pernikahan');
INSERT INTO "words" VALUES (412,'약','Yak','Obat');
INSERT INTO "words" VALUES (413,'감기','Gamgi','Flu / Masuk angin');
INSERT INTO "words" VALUES (414,'배','Bae','Perut / Kapal / Pir');
INSERT INTO "words" VALUES (415,'손가락','Son-garak','Jari tangan');
INSERT INTO "words" VALUES (416,'발가락','Bal-garak','Jari kaki');
INSERT INTO "words" VALUES (417,'무릎','Mureup','Lutut');
INSERT INTO "words" VALUES (418,'어깨','Eokkae','Bahu');
INSERT INTO "words" VALUES (419,'허리','Heori','Pinggang');
INSERT INTO "words" VALUES (420,'등','Deung','Punggung');
INSERT INTO "words" VALUES (421,'가슴','Gaseum','Dada');
INSERT INTO "words" VALUES (422,'피','Pi','Darah');
INSERT INTO "words" VALUES (423,'마음','Maeum','Hati');
INSERT INTO "words" VALUES (424,'기분','Gibun','Suasana hati / Perasaan');
INSERT INTO "words" VALUES (425,'기억','Gieok','Ingatan');
INSERT INTO "words" VALUES (426,'계획','Gyehoek','Rencana');
INSERT INTO "words" VALUES (427,'미래','Mirae','Masa depan');
INSERT INTO "words" VALUES (428,'과거','Gwageo','Masa lalu');
INSERT INTO "words" VALUES (429,'현재','Hyeonjae','Saat ini');
INSERT INTO "words" VALUES (430,'성격','Seonggyeok','Kepribadian');
INSERT INTO "words" VALUES (431,'습관','Seupgwan','Kebiasaan');
INSERT INTO "words" VALUES (432,'실수','Silsu','Kesalahan');
INSERT INTO "words" VALUES (433,'성공','Seonggong','Kesuksesan');
INSERT INTO "words" VALUES (434,'실패','Silpae','Kegagalan');
INSERT INTO "words" VALUES (435,'걱정','Geokjeong','Khawatir');
INSERT INTO "words" VALUES (436,'관심','Gwansim','Minat / Perhatian');
INSERT INTO "words" VALUES (437,'경험','Gyeongheom','Pengalaman');
INSERT INTO "words" VALUES (438,'이름','Ireum','Nama');
INSERT INTO "words" VALUES (439,'나이','Nai','Usia');
INSERT INTO "words" VALUES (440,'종이','Jongi','Kertas');
INSERT INTO "words" VALUES (441,'유리','Yuri','Kaca');
INSERT INTO "words" VALUES (442,'돌','Dol','Batu');
INSERT INTO "words" VALUES (443,'금','Geum','Emas');
INSERT INTO "words" VALUES (444,'은','Eun','Perak');
INSERT INTO "words" VALUES (445,'감정','Gamjeong','Emosi');
INSERT INTO "words" VALUES (446,'단어','Dane-o','Kata');
INSERT INTO "words" VALUES (447,'문장','Munjang','Kalimat');
INSERT INTO "words" VALUES (448,'말','Mal','Ucapan / Kuda');
INSERT INTO "words" VALUES (449,'글','Geul','Tulisan');
INSERT INTO "words" VALUES (450,'뜻','Tteut','Maksud / Arti');
INSERT INTO "words" VALUES (451,'소식','Sosik','Kabar');
INSERT INTO "words" VALUES (452,'정보','Jeongbo','Informasi');
INSERT INTO "words" VALUES (453,'지식','Jisik','Pengetahuan');
INSERT INTO "words" VALUES (454,'힘','Him','Kekuatan');
INSERT INTO "words" VALUES (455,'빛','Bit','Cahaya');
INSERT INTO "words" VALUES (456,'어둠','Eodum','Kegelapan');
INSERT INTO "words" VALUES (457,'처음','Cheo-eum','Pertama kali');
INSERT INTO "words" VALUES (458,'마지막','Majimak','Terakhir');
INSERT INTO "words" VALUES (459,'정부','Jeongbu','Pemerintah');
INSERT INTO "words" VALUES (460,'사회','Sahoe','Masyarakat');
INSERT INTO "words" VALUES (461,'경제','Gyeongje','Ekonomi');
INSERT INTO "words" VALUES (462,'문화','Munhwa','Budaya');
INSERT INTO "words" VALUES (463,'역사','Yeoksa','Sejarah');
INSERT INTO "words" VALUES (464,'과학','Gwahak','Sains');
INSERT INTO "words" VALUES (465,'기술','Gisul','Teknologi');
INSERT INTO "words" VALUES (466,'교육','Gyoyuk','Pendidikan');
INSERT INTO "words" VALUES (467,'환경','Hwan-gyeong','Lingkungan');
INSERT INTO "words" VALUES (468,'건강','Geon-gang','Kesehatan');
INSERT INTO "words" VALUES (469,'예술','Yesul','Seni');
INSERT INTO "words" VALUES (470,'음악가','Eumakga','Musisi');
INSERT INTO "words" VALUES (471,'화가','Hwaga','Pelukis');
INSERT INTO "words" VALUES (472,'작가','Jakga','Penulis');
INSERT INTO "words" VALUES (473,'배우','Bae-u','Aktor / Aktris');
INSERT INTO "words" VALUES (474,'직장','Jikjang','Tempat kerja');
INSERT INTO "words" VALUES (475,'동료','Dongnyo','Rekan kerja');
INSERT INTO "words" VALUES (476,'사장님','Sajangnim','Bos / Pemilik');
INSERT INTO "words" VALUES (477,'부장님','Bujangnim','Kepala departemen');
INSERT INTO "words" VALUES (478,'회의','Hoe-ui','Rapat');
INSERT INTO "words" VALUES (479,'보고서','Bogoseo','Laporan');
INSERT INTO "words" VALUES (480,'업무','Eommu','Tugas kerja');
INSERT INTO "words" VALUES (481,'출장','Chuljang','Perjalanan dinas');
INSERT INTO "words" VALUES (482,'월급','Wolgeup','Gaji');
INSERT INTO "words" VALUES (483,'보너스','Bboneoseu','Bonus');
INSERT INTO "words" VALUES (484,'승진','Seungjin','Promosi');
INSERT INTO "words" VALUES (485,'휴식','Hyusik','Istirahat');
INSERT INTO "words" VALUES (486,'스트레스','Seuteureseu','Stres');
INSERT INTO "words" VALUES (487,'취직','Chwijik','Mendapat pekerjaan');
INSERT INTO "words" VALUES (488,'퇴직','Toejik','Pensiun');
INSERT INTO "words" VALUES (489,'실업','Sireop','Pengangguran');
INSERT INTO "words" VALUES (490,'전공','Jeon-gong','Jurusan');
INSERT INTO "words" VALUES (491,'성적','Seongjeok','Nilai / Peringkat');
INSERT INTO "words" VALUES (492,'졸업','Joreop','Kelulusan');
INSERT INTO "words" VALUES (493,'입학','Ipak','Masuk sekolah');
INSERT INTO "words" VALUES (494,'대학교','Daehakgyo','Universitas');
INSERT INTO "words" VALUES (495,'고등학교','Godeunghakgyo','SMA');
INSERT INTO "words" VALUES (496,'중학교','Junghakgyo','SMP');
INSERT INTO "words" VALUES (497,'초등학교','Chodeunghakgyo','SD');
INSERT INTO "words" VALUES (498,'유치원','Yuchiwon','Taman kanak-kanak');
INSERT INTO "words" VALUES (499,'교수님','Gyosunim','Profesor');
INSERT INTO "words" VALUES (500,'강의','Gang-ui','Kuliah / Ceramah');
INSERT INTO "words" VALUES (501,'도서','Doseo','Buku (istilah formal)');
INSERT INTO "words" VALUES (502,'잡지','Japji','Majalah');
INSERT INTO "words" VALUES (503,'신문','Sinmun','Koran');
INSERT INTO "words" VALUES (504,'방송','Bangsong','Siaran');
INSERT INTO "words" VALUES (505,'광고','Gwanggo','Iklan');
INSERT INTO "words" VALUES (506,'인터넷','Inteonet','Internet');
INSERT INTO "words" VALUES (507,'웹사이트','Wepsaiteu','Situs web');
INSERT INTO "words" VALUES (508,'이메일','Imeil','Email');
INSERT INTO "words" VALUES (509,'비밀번호','Bimilbeonho','Kata sandi');
INSERT INTO "words" VALUES (510,'아이디','Aidi','ID / Nama pengguna');
INSERT INTO "words" VALUES (511,'컴퓨터 게임','Keompyuteo geim','Game komputer');
INSERT INTO "words" VALUES (512,'스마트폰','Seumateupon','Ponsel pintar');
INSERT INTO "words" VALUES (513,'앱','Aep','Aplikasi');
INSERT INTO "words" VALUES (514,'소셜 미디어','Sosyeol midieo','Media sosial');
INSERT INTO "words" VALUES (515,'댓글','Daetgeul','Komentar');
INSERT INTO "words" VALUES (516,'좋아요','Joayo','Suka (tombol)');
INSERT INTO "words" VALUES (517,'교통','Gyotong','Lalu lintas / Transportasi');
INSERT INTO "words" VALUES (518,'사고','Sago','Kecelakaan');
INSERT INTO "words" VALUES (519,'경찰','Gyeongchal','Polisi');
INSERT INTO "words" VALUES (520,'소방관','Sobanggwan','Pemadam kebakaran');
INSERT INTO "words" VALUES (521,'구급차','Gugeupcha','Ambulans');
INSERT INTO "words" VALUES (522,'범죄','Beomjoe','Kejahatan');
INSERT INTO "words" VALUES (523,'법','Beop','Hukum');
INSERT INTO "words" VALUES (524,'규칙','Gyuchik','Aturan');
INSERT INTO "words" VALUES (525,'벌금','Beolgeum','Denda');
INSERT INTO "words" VALUES (526,'세금','Segeum','Pajak');
INSERT INTO "words" VALUES (527,'현금','Hyeon-geum','Uang tunai');
INSERT INTO "words" VALUES (528,'신용카드','Sinyongkadeu','Kartu kredit');
INSERT INTO "words" VALUES (529,'계좌','Gyejwa','Rekening bank');
INSERT INTO "words" VALUES (530,'예금','Yegeum','Tabungan');
INSERT INTO "words" VALUES (531,'대출','Daechul','Pinjaman');
INSERT INTO "words" VALUES (532,'이자','Ija','Bunga (bank)');
INSERT INTO "words" VALUES (533,'투자','Tuja','Investasi');
INSERT INTO "words" VALUES (534,'주식','Jusik','Saham');
INSERT INTO "words" VALUES (535,'부동산','Budongsan','Properti');
INSERT INTO "words" VALUES (536,'아파트','Apateu','Apartemen');
INSERT INTO "words" VALUES (537,'빌라','Billa','Vila / Rumah susun');
INSERT INTO "words" VALUES (538,'주택','Jutaek','Rumah tinggal');
INSERT INTO "words" VALUES (539,'월세','Wolse','Sewa bulanan');
INSERT INTO "words" VALUES (540,'전세','Jeonse','Sewa (sistem Korea)');
INSERT INTO "words" VALUES (541,'계약','Gyeyak','Kontrak');
INSERT INTO "words" VALUES (542,'서명','Seomyeong','Tanda tangan');
INSERT INTO "words" VALUES (543,'신분증','Sinbunjeung','Kartu identitas');
INSERT INTO "words" VALUES (544,'여권','Yeogwon','Paspor');
INSERT INTO "words" VALUES (545,'비자','Bija','Visa');
INSERT INTO "words" VALUES (546,'국적','Gukjeok','Kewarganegaraan');
INSERT INTO "words" VALUES (547,'외국인','Oegugin','Orang asing');
INSERT INTO "words" VALUES (548,'국내','Gungnae','Domestik / Dalam negeri');
INSERT INTO "words" VALUES (549,'해외','Hae-oe','Luar negeri');
INSERT INTO "words" VALUES (550,'여행사','Yeohaengsa','Agen perjalanan');
INSERT INTO "words" VALUES (551,'항공권','Hang-gong-gwon','Tiket pesawat');
INSERT INTO "words" VALUES (552,'숙소','Sukso','Akomodasi / Penginapan');
INSERT INTO "words" VALUES (553,'호텔','Hotel','Hotel');
INSERT INTO "words" VALUES (554,'예약','Yeyak','Reservasi');
INSERT INTO "words" VALUES (555,'취소','Chwiso','Pembatalan');
INSERT INTO "words" VALUES (556,'짐','Jim','Bagasi');
INSERT INTO "words" VALUES (557,'포장','Pojang','Bungkusan / Kemasan');
INSERT INTO "words" VALUES (558,'배달','Baedal','Pengiriman');
INSERT INTO "words" VALUES (559,'주문','Jumun','Pesanan');
INSERT INTO "words" VALUES (560,'영수증','Yeongsujeung','Struk / Tanda terima');
INSERT INTO "words" VALUES (561,'계산','Gyesan','Perhitungan / Pembayaran');
INSERT INTO "words" VALUES (562,'결정하다','Gyeoljeonghada','Memutuskan');
INSERT INTO "words" VALUES (563,'선택하다','Seontaekada','Memilih');
INSERT INTO "words" VALUES (564,'설명하다','Seolmyeonghada','Menjelaskan');
INSERT INTO "words" VALUES (565,'이해하다','Ihaehada','Mengerti');
INSERT INTO "words" VALUES (566,'연락하다','Yeollakada','Menghubungi');
INSERT INTO "words" VALUES (567,'준비하다','Junbihada','Mempersiapkan');
INSERT INTO "words" VALUES (568,'사용하다','Sayonghada','Menggunakan');
INSERT INTO "words" VALUES (569,'빌리다','Billida','Meminjam');
INSERT INTO "words" VALUES (570,'돌려주다','Dollyeojuda','Mengembalikan');
INSERT INTO "words" VALUES (571,'버리다','Beorida','Membuang');
INSERT INTO "words" VALUES (572,'줍다','Jupda','Memungut');
INSERT INTO "words" VALUES (573,'놓다','Nota','Meletakkan');
INSERT INTO "words" VALUES (574,'옮기다','Omgida','Memindahkan');
INSERT INTO "words" VALUES (575,'바꾸다','Bakkuda','Mengubah / Menukar');
INSERT INTO "words" VALUES (576,'고치다','Gochida','Memperbaiki');
INSERT INTO "words" VALUES (577,'부수다','Busuda','Merusak');
INSERT INTO "words" VALUES (578,'잃어버리다','Ireobeorida','Kehilangan');
INSERT INTO "words" VALUES (579,'나가다','Nagada','Keluar');
INSERT INTO "words" VALUES (580,'들어가다','Deureogada','Masuk');
INSERT INTO "words" VALUES (581,'올라가다','Ollagada','Naik');
INSERT INTO "words" VALUES (582,'내려가다','Naeryeogada','Turun');
INSERT INTO "words" VALUES (583,'건너다','Geonneoda','Menyeberang');
INSERT INTO "words" VALUES (584,'지나다','Jinada','Melewati');
INSERT INTO "words" VALUES (585,'운전하다','Unjeonhada','Menyetir');
INSERT INTO "words" VALUES (586,'주차하다','Juchahada','Memarkir');
INSERT INTO "words" VALUES (587,'걱정하다','Geokjeonghada','Khawatir');
INSERT INTO "words" VALUES (588,'화나다','Hwanada','Marah');
INSERT INTO "words" VALUES (589,'싸우다','Ssauda','Berkelahi');
INSERT INTO "words" VALUES (590,'사과하다','Sagwahada','Meminta maaf');
INSERT INTO "words" VALUES (591,'용서하다','Yongseohada','Memaafkan');
INSERT INTO "words" VALUES (592,'칭찬하다','Chingchanhada','Memuji');
INSERT INTO "words" VALUES (593,'비판하다','Bipanhada','Mengkritik');
INSERT INTO "words" VALUES (594,'거짓말하다','Geojinmalhada','Berbohong');
INSERT INTO "words" VALUES (595,'약속하다','Yaksokada','Berjanji');
INSERT INTO "words" VALUES (596,'지키다','Jikida','Menepati / Melindungi');
INSERT INTO "words" VALUES (597,'어기다','Eogida','Mengingkari');
INSERT INTO "words" VALUES (598,'포기하다','Pogihada','Menyerah');
INSERT INTO "words" VALUES (599,'노력하다','Noryeokada','Berusaha');
INSERT INTO "words" VALUES (600,'성공하다','Seonggonghada','Berhasil');
INSERT INTO "words" VALUES (601,'실패하다','Silpaehada','Gagal');
INSERT INTO "words" VALUES (602,'꿈꾸다','Kkumkkuda','Bermimpi');
INSERT INTO "words" VALUES (603,'일어나다','Ireonada','Bangun tidur');
INSERT INTO "words" VALUES (604,'씻다','Ssitda','Mencuci (wajah, tangan)');
INSERT INTO "words" VALUES (605,'샤워하다','Syawohada','Mandi');
INSERT INTO "words" VALUES (606,'주문하다','Jumunhada','Memesan');
INSERT INTO "words" VALUES (607,'배달시키다','Baedalsikida','Memesan antar');
INSERT INTO "words" VALUES (608,'산책하다','Sanchaekada','Jalan-jalan');
INSERT INTO "words" VALUES (609,'등산하다','Deungsanhada','Mendaki gunung');
INSERT INTO "words" VALUES (610,'수영하다','Suyeonghada','Berenang');
INSERT INTO "words" VALUES (611,'사진 찍다','Sajin jjikda','Mengambil foto');
INSERT INTO "words" VALUES (612,'그림 그리다','Geurim geurida','Menggambar');
INSERT INTO "words" VALUES (613,'노래 부르다','Norae bureuda','Menyanyikan lagu');
INSERT INTO "words" VALUES (614,'악기를 연주하다','Akgireul yeonjuhada','Memainkan alat musik');
INSERT INTO "words" VALUES (615,'영화를 보다','Yeonghwareul boda','Menonton film');
INSERT INTO "words" VALUES (616,'책을 읽다','Chaegeul ikda','Membaca buku');
INSERT INTO "words" VALUES (617,'음악을 듣다','Eumageul deutda','Mendengarkan musik');
INSERT INTO "words" VALUES (618,'게임을 하다','Geimeul hada','Bermain game');
INSERT INTO "words" VALUES (619,'쇼핑하다','Syopinghada','Berbelanja');
INSERT INTO "words" VALUES (620,'여행하다','Yeohaenghada','Bepergian');
INSERT INTO "words" VALUES (621,'방문하다','Bangmunhada','Mengunjungi');
INSERT INTO "words" VALUES (622,'초대하다','Chodaehada','Mengundang');
INSERT INTO "words" VALUES (623,'참석하다','Chamseokada','Menghadiri');
INSERT INTO "words" VALUES (624,'결혼하다','Gyeolhonhada','Menikah');
INSERT INTO "words" VALUES (625,'이혼하다','Ihonhada','Bercerai');
INSERT INTO "words" VALUES (626,'태어나다','Taeeonada','Lahir');
INSERT INTO "words" VALUES (627,'죽다','Jukda','Meninggal');
INSERT INTO "words" VALUES (628,'빌려주다','Billyeojuda','Meminjamkan');
INSERT INTO "words" VALUES (629,'가져오다','Gajyeooda','Membawa (ke sini)');
INSERT INTO "words" VALUES (630,'가져가다','Gajyeogada','Membawa (ke sana)');
INSERT INTO "words" VALUES (631,'두다','Duda','Menaruh / Meninggalkan');
INSERT INTO "words" VALUES (632,'켜다','Kyeoda','Menyalakan');
INSERT INTO "words" VALUES (633,'끄다','Kkeuda','Mematikan');
INSERT INTO "words" VALUES (634,'설거지하다','Seolgeojihada','Mencuci piring');
INSERT INTO "words" VALUES (635,'빨래하다','Ppallaehada','Mencuci baju');
INSERT INTO "words" VALUES (636,'다리다','Darida','Menyetrika');
INSERT INTO "words" VALUES (637,'정리하다','Jeongnihada','Merapikan');
INSERT INTO "words" VALUES (638,'버스를 타다','Beoseureul tada','Naik bus');
INSERT INTO "words" VALUES (639,'택시를 잡다','Taeksireul japda','Menyetop taksi');
INSERT INTO "words" VALUES (640,'길을 잃다','Gireul ilta','Tersesat');
INSERT INTO "words" VALUES (641,'길을 묻다','Gireul mutda','Bertanya jalan');
INSERT INTO "words" VALUES (642,'예약하다','Yeyakada','Memesan / Reservasi');
INSERT INTO "words" VALUES (643,'취소하다','Chwisohada','Membatalkan');
INSERT INTO "words" VALUES (644,'확인하다','Hwaginada','Memastikan / Cek');
INSERT INTO "words" VALUES (645,'알려주다','Allyeojuda','Memberi tahu');
INSERT INTO "words" VALUES (646,'기다리다','Gidarida','Menunggu');
INSERT INTO "words" VALUES (647,'보이다','Boida','Terlihat');
INSERT INTO "words" VALUES (648,'들리다','Deullida','Terdengar');
INSERT INTO "words" VALUES (649,'느끼다','Neukkida','Merasakan');
INSERT INTO "words" VALUES (650,'냄새 맡다','Naemsae matda','Mencium bau');
INSERT INTO "words" VALUES (651,'맛보다','Matboda','Mencicipi');
INSERT INTO "words" VALUES (652,'만지다','Manjida','Menyentuh');
INSERT INTO "words" VALUES (653,'변하다','Byeonhada','Berubah');
INSERT INTO "words" VALUES (654,'계속하다','Gyesokada','Melanjutkan');
INSERT INTO "words" VALUES (655,'멈추다','Meomchuda','Berhenti');
INSERT INTO "words" VALUES (656,'쉬다','Swida','Beristirahat');
INSERT INTO "words" VALUES (657,'유명하다','Yumyeonghada','Terkenal');
INSERT INTO "words" VALUES (658,'친절하다','Chinjeolhada','Ramah');
INSERT INTO "words" VALUES (659,'불친절하다','Bulchinjeolhada','Tidak ramah');
INSERT INTO "words" VALUES (660,'위험하다','Wiheomhada','Berbahaya');
INSERT INTO "words" VALUES (661,'안전하다','Anjeonhada','Aman');
INSERT INTO "words" VALUES (662,'편리하다','Pyeollihada','Nyaman / Praktis');
INSERT INTO "words" VALUES (663,'불편하다','Bulpyeonhada','Tidak nyaman');
INSERT INTO "words" VALUES (664,'복잡하다','Bokjapada','Rumit / Ramai');
INSERT INTO "words" VALUES (665,'간단하다','Gandanada','Sederhana');
INSERT INTO "words" VALUES (666,'필요하다','Piryohada','Perlu / Dibutuhkan');
INSERT INTO "words" VALUES (667,'불필요하다','Bulpiryohada','Tidak perlu');
INSERT INTO "words" VALUES (668,'중요하다','Jungyohada','Penting');
INSERT INTO "words" VALUES (669,'가능하다','Ganeunghada','Mungkin');
INSERT INTO "words" VALUES (670,'불가능하다','Bulganeunghada','Tidak mungkin');
INSERT INTO "words" VALUES (671,'건강하다','Geon-ganghada','Sehat');
INSERT INTO "words" VALUES (672,'다양하다','Dayanghada','Beragam');
INSERT INTO "words" VALUES (673,'특별하다','Teukbyeolhada','Istimewa');
INSERT INTO "words" VALUES (674,'평범하다','Pyeongbeomhada','Biasa');
INSERT INTO "words" VALUES (675,'자유롭다','Jayuropda','Bebas');
INSERT INTO "words" VALUES (676,'답답하다','Dapdapada','Frustasi / Sesak');
INSERT INTO "words" VALUES (677,'부끄럽다','Bukkeureopda','Malu');
INSERT INTO "words" VALUES (678,'창피하다','Changpihada','Memalukan');
INSERT INTO "words" VALUES (679,'놀랍다','Nollapda','Mengejutkan / Luar biasa');
INSERT INTO "words" VALUES (680,'신기하다','Singihada','Ajaib / Menakjubkan');
INSERT INTO "words" VALUES (681,'이상하다','Isanghada','Aneh');
INSERT INTO "words" VALUES (682,'어색하다','Eosaekada','Canggung');
INSERT INTO "words" VALUES (683,'익숙하다','Iksukada','Terbiasa');
INSERT INTO "words" VALUES (684,'낯설다','Natseolda','Asing / Tidak familiar');
INSERT INTO "words" VALUES (685,'궁금하다','Gung-geumhada','Penasaran');
INSERT INTO "words" VALUES (686,'걱정되다','Geokjeongdoeda','Khawatir');
INSERT INTO "words" VALUES (687,'기대되다','Gidaedoeda','Tidak sabar / Menanti-nanti');
INSERT INTO "words" VALUES (688,'실망하다','Silmanghada','Kecewa');
INSERT INTO "words" VALUES (689,'만족하다','Manjokada','Puas');
INSERT INTO "words" VALUES (690,'불만족스럽다','Bulmanjokseureopda','Tidak memuaskan');
INSERT INTO "words" VALUES (691,'지루하다','Jiruhada','Bosan');
INSERT INTO "words" VALUES (692,'신나다','Sinnada','Gembira / Bersemangat');
INSERT INTO "words" VALUES (693,'우울하다','U-ulhada','Depresi / Murung');
INSERT INTO "words" VALUES (694,'외롭다','Oeropda','Kesepian');
INSERT INTO "words" VALUES (695,'그립다','Geuripda','Rindu');
INSERT INTO "words" VALUES (696,'무섭다','Museopda','Takut');
INSERT INTO "words" VALUES (697,'용감하다','Yong-gamhada','Berani');
INSERT INTO "words" VALUES (698,'부지런하다','Bujireonhada','Rajin');
INSERT INTO "words" VALUES (699,'게으르다','Ge-eureuda','Malas');
INSERT INTO "words" VALUES (700,'솔직하다','Soljikada','Jujur');
INSERT INTO "words" VALUES (701,'정직하다','Jeongjikada','Jujur');
INSERT INTO "words" VALUES (702,'부드럽다','Budeureopda','Lembut');
INSERT INTO "words" VALUES (703,'딱딱하다','Ttakttakada','Keras');
INSERT INTO "words" VALUES (704,'시원하다','Siwonhada','Sejuk');
INSERT INTO "words" VALUES (705,'따뜻하다','Ttatteuthada','Hangat');
INSERT INTO "words" VALUES (706,'밝다','Bakda','Terang');
INSERT INTO "words" VALUES (707,'어둡다','Eodupda','Gelap');
INSERT INTO "words" VALUES (708,'두껍다','Dukkeopda','Tebal');
INSERT INTO "words" VALUES (709,'얇다','Yaltta','Tipis');
INSERT INTO "words" VALUES (710,'넓다','Neolda','Luas');
INSERT INTO "words" VALUES (711,'좁다','Jopda','Sempit');
INSERT INTO "words" VALUES (712,'젖다','Jeotda','Basah');
INSERT INTO "words" VALUES (713,'마르다','Mareuda','Kering / Kurus');
INSERT INTO "words" VALUES (714,'뚱뚱하다','Ttungttunghada','Gemuk');
INSERT INTO "words" VALUES (715,'날씬하다','Nalssinhada','Ramping');
INSERT INTO "words" VALUES (716,'젊다','Jeomda','Muda');
INSERT INTO "words" VALUES (717,'늙다','Neukda','Tua');
INSERT INTO "words" VALUES (718,'강하다','Ganghada','Kuat');
INSERT INTO "words" VALUES (719,'약하다','Yakhada','Lemah');
INSERT INTO "words" VALUES (720,'달다','Dalda','Manis');
INSERT INTO "words" VALUES (721,'쓰다','Sseuda','Pahit');
INSERT INTO "words" VALUES (722,'짜다','Jjada','Asin');
INSERT INTO "words" VALUES (723,'시다','Sida','Asam');
INSERT INTO "words" VALUES (724,'맵다','Maepda','Pedas');
INSERT INTO "words" VALUES (725,'싱겁다','Sing-geopda','Hambar');
INSERT INTO "words" VALUES (726,'빨리','Ppalli','Dengan cepat');
INSERT INTO "words" VALUES (727,'천천히','Cheoncheonhi','Dengan pelan');
INSERT INTO "words" VALUES (728,'많이','Mani','Banyak (kuantitas)');
INSERT INTO "words" VALUES (729,'조금','Jogeum','Sedikit');
INSERT INTO "words" VALUES (730,'잘','Jal','Dengan baik');
INSERT INTO "words" VALUES (731,'못','Mot','Tidak bisa');
INSERT INTO "words" VALUES (732,'안','An','Tidak (untuk kata kerja/sifat)');
INSERT INTO "words" VALUES (733,'열심히','Yeolsimhi','Dengan giat');
INSERT INTO "words" VALUES (734,'조용히','Joyonghi','Dengan tenang');
INSERT INTO "words" VALUES (735,'갑자기','Gapjagi','Tiba-tiba');
INSERT INTO "words" VALUES (736,'방금','Banggeum','Baru saja');
INSERT INTO "words" VALUES (737,'아까','Akka','Tadi');
INSERT INTO "words" VALUES (738,'이따가','Ittaga','Nanti');
INSERT INTO "words" VALUES (739,'나중에','Najunge','Nanti (waktu yang lebih jauh)');
INSERT INTO "words" VALUES (740,'먼저','Meonjeo','Duluan');
INSERT INTO "words" VALUES (741,'이미','Imi','Sudah');
INSERT INTO "words" VALUES (742,'벌써','Beolsseo','Sudah (menunjukkan keterkejutan)');
INSERT INTO "words" VALUES (743,'아직','Ajik','Masih / Belum');
INSERT INTO "words" VALUES (744,'항상','Hangsang','Selalu');
INSERT INTO "words" VALUES (745,'매일','Maeil','Setiap hari');
INSERT INTO "words" VALUES (746,'거의','Geoui','Hampir');
INSERT INTO "words" VALUES (747,'전혀','Jeonhyeo','Sama sekali tidak');
INSERT INTO "words" VALUES (748,'별로','Byeollo','Tidak begitu');
INSERT INTO "words" VALUES (749,'직접','Jikjeop','Langsung');
INSERT INTO "words" VALUES (750,'따로','Ttaro','Terpisah');
INSERT INTO "words" VALUES (751,'함께','Hamkke','Bersama');
INSERT INTO "words" VALUES (752,'다시','Dasi','Lagi');
INSERT INTO "words" VALUES (753,'또','Tto','Lagi / Juga');
INSERT INTO "words" VALUES (754,'계속','Gyesok','Terus-menerus');
INSERT INTO "words" VALUES (755,'그냥','Geunyang','Begitu saja');
INSERT INTO "words" VALUES (756,'꼭','Kkok','Pasti / Harus');
INSERT INTO "words" VALUES (757,'아마도','Amado','Mungkin');
INSERT INTO "words" VALUES (758,'물론','Mullon','Tentu saja');
INSERT INTO "words" VALUES (759,'만약','Manyak','Jika / Seandainya');
INSERT INTO "words" VALUES (760,'혹시','Hoksi','Mungkin / Barangkali (saat bertanya)');
INSERT INTO "words" VALUES (761,'대통령','Daetongnyeong','Presiden');
INSERT INTO "words" VALUES (762,'정치','Jeongchi','Politik');
INSERT INTO "words" VALUES (763,'선거','Seon-geo','Pemilihan umum');
INSERT INTO "words" VALUES (764,'투표하다','Tupyohada','Memberi suara');
INSERT INTO "words" VALUES (765,'국회','Gukhoe','Parlemen');
INSERT INTO "words" VALUES (766,'법원','Beobwon','Pengadilan');
INSERT INTO "words" VALUES (767,'판사','Pansa','Hakim');
INSERT INTO "words" VALUES (768,'변호사','Byeonhosa','Pengacara');
INSERT INTO "words" VALUES (769,'검사','Geomsa','Jaksa');
INSERT INTO "words" VALUES (770,'증거','Jeung-geo','Bukti');
INSERT INTO "words" VALUES (771,'수사','Susa','Investigasi');
INSERT INTO "words" VALUES (772,'군대','Gundae','Militer');
INSERT INTO "words" VALUES (773,'군인','Gunin','Tentara');
INSERT INTO "words" VALUES (774,'전쟁','Jeonjaeng','Perang');
INSERT INTO "words" VALUES (775,'평화','Pyeonghwa','Perdamaian');
INSERT INTO "words" VALUES (776,'국제','Gukje','Internasional');
INSERT INTO "words" VALUES (777,'관계','Gwangye','Hubungan');
INSERT INTO "words" VALUES (778,'협상','Hyeopsang','Negosiasi');
INSERT INTO "words" VALUES (779,'조약','Joyak','Perjanjian');
INSERT INTO "words" VALUES (780,'수출','Suchul','Ekspor');
INSERT INTO "words" VALUES (781,'수입','Su-ip','Impor');
INSERT INTO "words" VALUES (782,'무역','Muyeok','Perdagangan');
INSERT INTO "words" VALUES (783,'환율','Hwanyul','Nilai tukar');
INSERT INTO "words" VALUES (784,'주가','Juga','Harga saham');
INSERT INTO "words" VALUES (785,'기업','Gieop','Perusahaan / Korporasi');
INSERT INTO "words" VALUES (786,'제품','Jepum','Produk');
INSERT INTO "words" VALUES (787,'서비스','Seobiseu','Layanan');
INSERT INTO "words" VALUES (788,'고객','Gogaek','Pelanggan');
INSERT INTO "words" VALUES (789,'소비자','Sobija','Konsumen');
INSERT INTO "words" VALUES (790,'생산','Saengsan','Produksi');
INSERT INTO "words" VALUES (791,'개발','Gaebal','Pengembangan');
INSERT INTO "words" VALUES (792,'연구','Yeon-gu','Penelitian');
INSERT INTO "words" VALUES (793,'디자인','Dijain','Desain');
INSERT INTO "words" VALUES (794,'품질','Pumjil','Kualitas');
INSERT INTO "words" VALUES (795,'할인','Harin','Diskon');
INSERT INTO "words" VALUES (796,'결제','Gyeolje','Pembayaran');
INSERT INTO "words" VALUES (797,'배송','Baesong','Pengiriman');
INSERT INTO "words" VALUES (798,'반품','Banpum','Pengembalian barang');
INSERT INTO "words" VALUES (799,'환불','Hwanbul','Pengembalian dana');
INSERT INTO "words" VALUES (800,'예술가','Yesulga','Seniman');
INSERT INTO "words" VALUES (801,'작품','Jakpum','Karya seni');
INSERT INTO "words" VALUES (802,'전시회','Jeonsihoe','Pameran');
INSERT INTO "words" VALUES (803,'박물관','Bangmulgwan','Museum');
INSERT INTO "words" VALUES (804,'미술관','Misulgwan','Galeri seni');
INSERT INTO "words" VALUES (805,'공연','Gong-yeon','Pertunjukan');
INSERT INTO "words" VALUES (806,'콘서트','Konseoteu','Konser');
INSERT INTO "words" VALUES (807,'연극','Yeon-geuk','Teater');
INSERT INTO "words" VALUES (808,'뮤지컬','Myujikeol','Musikal');
INSERT INTO "words" VALUES (809,'감독','Gamdok','Sutradara');
INSERT INTO "words" VALUES (810,'주연','Juyeon','Pemeran utama');
INSERT INTO "words" VALUES (811,'조연','Joyeon','Pemeran pendukung');
INSERT INTO "words" VALUES (812,'음반','Eumban','Album musik');
INSERT INTO "words" VALUES (813,'가사','Gasa','Lirik');
INSERT INTO "words" VALUES (814,'멜로디','Mellodi','Melodi');
INSERT INTO "words" VALUES (815,'소설','Soseol','Novel');
INSERT INTO "words" VALUES (816,'시','Si','Puisi');
INSERT INTO "words" VALUES (817,'수필','Supil','Esai');
INSERT INTO "words" VALUES (818,'문학','Munhak','Sastra');
INSERT INTO "words" VALUES (819,'철학','Cheolhak','Filsafat');
INSERT INTO "words" VALUES (820,'심리학','Simnihak','Psikologi');
INSERT INTO "words" VALUES (821,'사회학','Sahoehak','Sosiologi');
INSERT INTO "words" VALUES (822,'의학','Uihak','Ilmu kedokteran');
INSERT INTO "words" VALUES (823,'물리학','Mullihak','Fisika');
INSERT INTO "words" VALUES (824,'화학','Hwahak','Kimia');
INSERT INTO "words" VALUES (825,'생물학','Saengmulhak','Biologi');
INSERT INTO "words" VALUES (826,'지구과학','Jigugwahak','Ilmu bumi');
INSERT INTO "words" VALUES (827,'우주','Uju','Luar angkasa');
INSERT INTO "words" VALUES (828,'행성','Haengseong','Planet');
INSERT INTO "words" VALUES (829,'은하','Eunha','Galaksi');
INSERT INTO "words" VALUES (830,'인공위성','In-gong-wiseong','Satelit');
INSERT INTO "words" VALUES (831,'로봇','Robot','Robot');
INSERT INTO "words" VALUES (832,'인공지능','In-gongjineung','Kecerdasan buatan');
INSERT INTO "words" VALUES (833,'데이터','Deiteo','Data');
INSERT INTO "words" VALUES (834,'알고리즘','Algorijeum','Algoritma');
INSERT INTO "words" VALUES (835,'소프트웨어','Sopeuteuwe-eo','Perangkat lunak');
INSERT INTO "words" VALUES (836,'하드웨어','Hadeuwe-eo','Perangkat keras');
INSERT INTO "words" VALUES (837,'바이러스','Baireoseu','Virus');
INSERT INTO "words" VALUES (838,'해킹','Haeking','Peretasan');
INSERT INTO "words" VALUES (839,'보안','Boan','Keamanan');
INSERT INTO "words" VALUES (840,'자연','Jayeon','Alam');
INSERT INTO "words" VALUES (841,'재해','Jaehae','Bencana');
INSERT INTO "words" VALUES (842,'지진','Jijin','Gempa bumi');
INSERT INTO "words" VALUES (843,'홍수','Hongsu','Banjir');
INSERT INTO "words" VALUES (844,'가뭄','Gamum','Kekeringan');
INSERT INTO "words" VALUES (845,'태풍','Taepung','Topan');
INSERT INTO "words" VALUES (846,'화산','Hwasan','Gunung berapi');
INSERT INTO "words" VALUES (847,'기후','Gihu','Iklim');
INSERT INTO "words" VALUES (848,'변화','Byeonhwa','Perubahan');
INSERT INTO "words" VALUES (849,'온난화','Onnanhwa','Pemanasan global');
INSERT INTO "words" VALUES (850,'오염','Oyeom','Polusi');
INSERT INTO "words" VALUES (851,'재활용','Jaehwalyong','Daur ulang');
INSERT INTO "words" VALUES (852,'에너지','Eneoji','Energi');
INSERT INTO "words" VALUES (853,'전기','Jeon-gi','Listrik');
INSERT INTO "words" VALUES (854,'가스','Gaseu','Gas');
INSERT INTO "words" VALUES (855,'수도','Sudo','Air ledeng');
INSERT INTO "words" VALUES (856,'쓰레기','Sseuregi','Sampah');
INSERT INTO "words" VALUES (857,'질병','Jilbyeong','Penyakit');
INSERT INTO "words" VALUES (858,'암','Am','Kanker');
INSERT INTO "words" VALUES (859,'당뇨병','Dangnyobyeong','Diabetes');
INSERT INTO "words" VALUES (860,'심장병','Simjangbyeong','Penyakit jantung');
INSERT INTO "words" VALUES (861,'증상','Jeungsang','Gejala');
INSERT INTO "words" VALUES (862,'치료','Chiryo','Pengobatan');
INSERT INTO "words" VALUES (863,'수술','Susul','Operasi');
INSERT INTO "words" VALUES (864,'예방','Yebang','Pencegahan');
INSERT INTO "words" VALUES (865,'백신','Baeksin','Vaksin');
INSERT INTO "words" VALUES (866,'정신','Jeongsin','Mental / Jiwa');
INSERT INTO "words" VALUES (867,'상담','Sangdam','Konseling');
INSERT INTO "words" VALUES (868,'기침','Gichim','Batuk');
INSERT INTO "words" VALUES (869,'열','Yeol','Demam');
INSERT INTO "words" VALUES (870,'두통','Dutong','Sakit kepala');
INSERT INTO "words" VALUES (871,'복통','Boktong','Sakit perut');
INSERT INTO "words" VALUES (872,'치통','Chitong','Sakit gigi');
INSERT INTO "words" VALUES (873,'알레르기','Allereugi','Alergi');
INSERT INTO "words" VALUES (874,'소화','Sohwa','Pencernaan');
INSERT INTO "words" VALUES (875,'비타민','Bitamin','Vitamin');
INSERT INTO "words" VALUES (876,'식단','Sikdan','Pola makan');
INSERT INTO "words" VALUES (877,'다이어트','Daieoteu','Diet');
INSERT INTO "words" VALUES (878,'수면','Sumyeon','Tidur');
INSERT INTO "words" VALUES (879,'전통','Jeontong','Tradisi');
INSERT INTO "words" VALUES (880,'명절','Myeongjeol','Hari raya');
INSERT INTO "words" VALUES (881,'설날','Seollal','Tahun Baru Imlek');
INSERT INTO "words" VALUES (882,'추석','Chuseok','Hari Chuseok (panen)');
INSERT INTO "words" VALUES (883,'한복','Hanbok','Pakaian tradisional Korea');
INSERT INTO "words" VALUES (884,'김장','Gimjang','Tradisi membuat kimchi');
INSERT INTO "words" VALUES (885,'민속','Minsok','Rakyat');
INSERT INTO "words" VALUES (886,'신화','Sinhwa','Mitos');
INSERT INTO "words" VALUES (887,'전설','Jeonseol','Legenda');
INSERT INTO "words" VALUES (888,'종교','Jonggyo','Agama');
INSERT INTO "words" VALUES (889,'불교','Bulgyo','Buddhisme');
INSERT INTO "words" VALUES (890,'기독교','Gidokgyo','Kristen');
INSERT INTO "words" VALUES (891,'절','Jeol','Kuil Buddha');
INSERT INTO "words" VALUES (892,'교회','Gyohoe','Gereja');
INSERT INTO "words" VALUES (893,'성당','Seongdang','Katedral');
INSERT INTO "words" VALUES (894,'기도','Gido','Doa');
INSERT INTO "words" VALUES (895,'믿음','Mideum','Kepercayaan');
INSERT INTO "words" VALUES (896,'행운','Haeng-un','Keberuntungan');
INSERT INTO "words" VALUES (897,'불운','Burun','Nasib buruk');
INSERT INTO "words" VALUES (898,'운명','Unmyeong','Takdir');
INSERT INTO "words" VALUES (899,'미신','Misin','Takhayul');
INSERT INTO "words" VALUES (900,'표정','Pyojeong','Ekspresi wajah');
INSERT INTO "words" VALUES (901,'웃음','Useum','Tawa');
INSERT INTO "words" VALUES (902,'눈물','Nunmul','Air mata');
INSERT INTO "words" VALUES (903,'기쁨','Gippeum','Kegembiraan');
INSERT INTO "words" VALUES (904,'슬픔','Seulpeum','Kesedihan');
INSERT INTO "words" VALUES (905,'화','Hwa','Kemarahan');
INSERT INTO "words" VALUES (906,'공포','Gongpo','Ketakutan');
INSERT INTO "words" VALUES (907,'놀람','Nollam','Keterkejutan');
INSERT INTO "words" VALUES (908,'질투','Jiltu','Cemburu');
INSERT INTO "words" VALUES (909,'부러움','Bureoum','Iri');
INSERT INTO "words" VALUES (910,'후회','Huhoe','Penyesalan');
INSERT INTO "words" VALUES (911,'절망','Jeolmang','Keputusasaan');
INSERT INTO "words" VALUES (912,'만족','Manjok','Kepuasan');
INSERT INTO "words" VALUES (913,'불만','Bulman','Ketidakpuasan');
INSERT INTO "words" VALUES (914,'자신감','Jasin-gam','Kepercayaan diri');
INSERT INTO "words" VALUES (915,'열정','Yeoljeong','Semangat');
INSERT INTO "words" VALUES (916,'의지','Uiji','Keinginan / Tekad');
INSERT INTO "words" VALUES (917,'용기','Yong-gi','Keberanian');
INSERT INTO "words" VALUES (918,'외향적','Oehyangjeok','Ekstrovert');
INSERT INTO "words" VALUES (919,'내성적','Naeseongjeok','Introvert');
INSERT INTO "words" VALUES (920,'긍정적','Geungjeongjeok','Positif');
INSERT INTO "words" VALUES (921,'부정적','Bujeongjeok','Negatif');
INSERT INTO "words" VALUES (922,'낙관적','Nakgwanjeok','Optimis');
INSERT INTO "words" VALUES (923,'비관적','Bigwanjeok','Pesimis');
INSERT INTO "words" VALUES (924,'활발하다','Hwalbalhada','Aktif');
INSERT INTO "words" VALUES (925,'조용하다','Joyonghada','Pendiam');
INSERT INTO "words" VALUES (926,'사교적','Sagyojeok','Sosial');
INSERT INTO "words" VALUES (927,'이기적','Igijeok','Egois');
INSERT INTO "words" VALUES (928,'이타적','Itajeok','Altruis');
INSERT INTO "words" VALUES (929,'고집이 세다','Gojibi seda','Keras kepala');
INSERT INTO "words" VALUES (930,'책임감','Chaegimgam','Rasa tanggung jawab');
INSERT INTO "words" VALUES (931,'유머','Yumeo','Humor');
INSERT INTO "words" VALUES (932,'감각','Gamgak','Indra');
INSERT INTO "words" VALUES (933,'시각','Sigak','Penglihatan');
INSERT INTO "words" VALUES (934,'청각','Cheonggak','Pendengaran');
INSERT INTO "words" VALUES (935,'후각','Hugak','Penciuman');
INSERT INTO "words" VALUES (936,'미각','Migak','Pengecapan');
INSERT INTO "words" VALUES (937,'촉각','Chokgak','Peraba');
INSERT INTO "words" VALUES (938,'외모','Oemo','Penampilan');
INSERT INTO "words" VALUES (939,'키','Ki','Tinggi badan');
INSERT INTO "words" VALUES (940,'몸무게','Mommuge','Berat badan');
INSERT INTO "words" VALUES (941,'머리카락','Meorikarak','Rambut');
INSERT INTO "words" VALUES (942,'피부','Pibu','Kulit');
INSERT INTO "words" VALUES (943,'패션','Paesyeon','Mode');
INSERT INTO "words" VALUES (944,'스타일','Seutail','Gaya');
INSERT INTO "words" VALUES (945,'화장','Hwajang','Riasan');
INSERT INTO "words" VALUES (946,'성형','Seonghyeong','Operasi plastik');
INSERT INTO "words" VALUES (947,'자세','Jase','Postur');
INSERT INTO "words" VALUES (948,'표현','Pyohyeon','Ekspresi / Ungkapan');
INSERT INTO "words" VALUES (949,'의견','Uigyeon','Pendapat');
INSERT INTO "words" VALUES (950,'주장','Jujang','Argumen');
INSERT INTO "words" VALUES (951,'토론','Toron','Debat');
INSERT INTO "words" VALUES (952,'비판','Bipan','Kritik');
INSERT INTO "words" VALUES (953,'칭찬','Chingchan','Pujian');
INSERT INTO "words" VALUES (954,'조언','Jo-eon','Nasihat');
INSERT INTO "words" VALUES (955,'제안','Jean','Saran / Proposal');
INSERT INTO "words" VALUES (956,'설득','Seoltteuk','Bujukan');
INSERT INTO "words" VALUES (957,'거절','Geojeol','Penolakan');
INSERT INTO "words" VALUES (958,'동의','Dong-ui','Persetujuan');
INSERT INTO "words" VALUES (959,'반대','Bandae','Oposisi');
INSERT INTO "words" VALUES (960,'갈등','Galdeung','Konflik');
INSERT INTO "words" VALUES (961,'해결','Haegyeol','Solusi');
INSERT INTO "words" VALUES (962,'협력','Hyeomnyeok','Kerja sama');
INSERT INTO "words" VALUES (963,'경쟁','Gyeongjaeng','Kompetisi');
INSERT INTO "words" VALUES (964,'승리','Seungni','Kemenangan');
INSERT INTO "words" VALUES (965,'패배','Paebae','Kekalahan');
INSERT INTO "words" VALUES (966,'목표','Mokpyo','Tujuan');
INSERT INTO "words" VALUES (967,'과정','Gwajjeong','Proses');
INSERT INTO "words" VALUES (968,'결과','Gyeolgwa','Hasil');
INSERT INTO "words" VALUES (969,'원인','Wonin','Penyebab');
INSERT INTO "words" VALUES (970,'영향','Yeonghyang','Pengaruh');
INSERT INTO "words" VALUES (971,'효과','Hyogwa','Efek');
INSERT INTO "words" VALUES (972,'장점','Jangjeom','Kelebihan');
INSERT INTO "words" VALUES (973,'단점','Danjeom','Kekurangan');
INSERT INTO "words" VALUES (974,'특징','Teukjing','Ciri khas');
INSERT INTO "words" VALUES (975,'차이','Chai','Perbedaan');
INSERT INTO "words" VALUES (976,'공통점','Gongtongjeom','Persamaan');
INSERT INTO "words" VALUES (977,'수준','Sujun','Tingkat / Level');
INSERT INTO "words" VALUES (978,'정도','Jeongdo','Tingkat / Derajat');
INSERT INTO "words" VALUES (979,'규모','Gyumo','Skala');
INSERT INTO "words" VALUES (980,'양','Yang','Jumlah / Kuantitas');
INSERT INTO "words" VALUES (981,'질','Jil','Kualitas');
INSERT INTO "words" VALUES (982,'순서','Sunseo','Urutan');
INSERT INTO "words" VALUES (983,'위치','Wichi','Posisi / Lokasi');
INSERT INTO "words" VALUES (984,'방향','Banghyang','Arah');
INSERT INTO "words" VALUES (985,'거리','Geori','Jarak');
INSERT INTO "words" VALUES (986,'속도','Sokdo','Kecepatan');
INSERT INTO "words" VALUES (987,'무게','Muge','Berat');
INSERT INTO "words" VALUES (988,'온도','Ondo','Suhu');
INSERT INTO "words" VALUES (989,'압력','Amnyeok','Tekanan');
INSERT INTO "words" VALUES (990,'소금','Sogeum','Garam');
INSERT INTO "words" VALUES (991,'설탕','Seoltang','Gula');
INSERT INTO "words" VALUES (992,'후추','Huchu','Lada');
INSERT INTO "words" VALUES (993,'고추','Gochu','Cabai');
INSERT INTO "words" VALUES (994,'마늘','Maneul','Bawang putih');
INSERT INTO "words" VALUES (995,'양파','Yangpa','Bawang bombay');
INSERT INTO "words" VALUES (996,'감자','Gamja','Kentang');
INSERT INTO "words" VALUES (997,'고구마','Goguma','Ubi');
INSERT INTO "words" VALUES (998,'당근','Dang-geun','Wortel');
INSERT INTO "words" VALUES (999,'오이','Oi','Timun');
INSERT INTO "words" VALUES (1000,'토마토','Tomato','Tomat');
INSERT INTO "words" VALUES (1001,'상추','Sangchu','Selada');
INSERT INTO "words" VALUES (1002,'계란','Gyeran','Telur');
INSERT INTO "words" VALUES (1003,'닭고기','Dakgogi','Daging ayam');
INSERT INTO "words" VALUES (1004,'소고기','Sogogi','Daging sapi');
INSERT INTO "words" VALUES (1005,'돼지고기','Dwaejigogi','Daging babi');
INSERT INTO "words" VALUES (1006,'양고기','Yanggogi','Daging domba');
INSERT INTO "words" VALUES (1007,'해산물','Haesanmul','Makanan laut');
INSERT INTO "words" VALUES (1008,'새우','Sae-u','Udang');
INSERT INTO "words" VALUES (1009,'게','Ge','Kepiting');
INSERT INTO "words" VALUES (1010,'오징어','Ojingeo','Cumi-cumi');
INSERT INTO "words" VALUES (1011,'조개','Jogae','Kerang');
INSERT INTO "words" VALUES (1012,'국','Guk','Sup (encer)');
INSERT INTO "words" VALUES (1013,'탕','Tang','Sup (kental)');
INSERT INTO "words" VALUES (1014,'찌개','Jjigae','Sup rebusan');
INSERT INTO "words" VALUES (1015,'반찬','Banchan','Lauk pauk');
INSERT INTO "words" VALUES (1016,'간식','Gansik','Camilan');
INSERT INTO "words" VALUES (1017,'음료수','Eumryosu','Minuman ringan');
INSERT INTO "words" VALUES (1018,'술','Sul','Alkohol');
INSERT INTO "words" VALUES (1019,'맥주','Maekju','Bir');
INSERT INTO "words" VALUES (1020,'소주','Soju','Soju');
INSERT INTO "words" VALUES (1021,'와인','Wain','Anggur (minuman)');
INSERT INTO "words" VALUES (1022,'아이스크림','Aiseukeulim','Es krim');
INSERT INTO "words" VALUES (1023,'케이크','Keikeu','Kue');
INSERT INTO "words" VALUES (1024,'과자','Gwaja','Biskuit / Keripik');
INSERT INTO "words" VALUES (1025,'사탕','Satang','Permen');
INSERT INTO "words" VALUES (1026,'초콜릿','Chokollit','Cokelat');
INSERT INTO "words" VALUES (1027,'계절','Gyejeol','Musim');
INSERT INTO "words" VALUES (1028,'하늘','Haneul','Langit');
INSERT INTO "words" VALUES (1029,'땅','Ttang','Tanah');
INSERT INTO "words" VALUES (1030,'물','Mul','Air');
INSERT INTO "words" VALUES (1031,'불','Bul','Api');
INSERT INTO "words" VALUES (1032,'공기','Gong-gi','Udara');
INSERT INTO "words" VALUES (1033,'바람','Baram','Angin');
INSERT INTO "words" VALUES (1034,'햇빛','Haetbit','Sinar matahari');
INSERT INTO "words" VALUES (1035,'그림자','Geurimja','Bayangan');
INSERT INTO "words" VALUES (1036,'먼지','Meonji','Debu');
INSERT INTO "words" VALUES (1037,'안개','An-gae','Kabut');
INSERT INTO "words" VALUES (1038,'천둥','Cheondung','Guntur');
INSERT INTO "words" VALUES (1039,'번개','Beon-gae','Petir');
INSERT INTO "words" VALUES (1040,'무지개','Mujigae','Pelangi');
INSERT INTO "words" VALUES (1041,'섬','Seom','Pulau');
INSERT INTO "words" VALUES (1042,'육지','Yukji','Daratan');
INSERT INTO "words" VALUES (1043,'해변','Haebyeon','Pantai');
INSERT INTO "words" VALUES (1044,'사막','Samak','Gurun');
INSERT INTO "words" VALUES (1045,'숲','Sup','Hutan');
INSERT INTO "words" VALUES (1046,'정글','Jeonggeul','Hutan rimba');
INSERT INTO "words" VALUES (1047,'들','Deul','Padang');
INSERT INTO "words" VALUES (1048,'호수','Hosu','Danau');
INSERT INTO "words" VALUES (1049,'연못','Yeonmot','Kolam');
INSERT INTO "words" VALUES (1050,'폭포','Pokpo','Air terjun');
INSERT INTO "words" VALUES (1051,'계곡','Gyegok','Lembah');
INSERT INTO "words" VALUES (1052,'동굴','Dong-gul','Gua');
INSERT INTO "words" VALUES (1053,'화초','Hwacho','Tanaman hias');
INSERT INTO "words" VALUES (1054,'잔디','Jandi','Rumput');
INSERT INTO "words" VALUES (1055,'뿌리','Ppuri','Akar');
INSERT INTO "words" VALUES (1056,'줄기','Julgi','Batang');
INSERT INTO "words" VALUES (1057,'잎','Ip','Daun');
INSERT INTO "words" VALUES (1058,'씨앗','Ssi-at','Biji');
INSERT INTO "words" VALUES (1059,'농장','Nongjang','Peternakan');
INSERT INTO "words" VALUES (1060,'농부','Nongbu','Petani');
INSERT INTO "words" VALUES (1061,'수확','Suhwak','Panen');
INSERT INTO "words" VALUES (1062,'곤충','Gonchung','Serangga');
INSERT INTO "words" VALUES (1063,'벌레','Beolle','Ulat / Serangga');
INSERT INTO "words" VALUES (1064,'나비','Nabi','Kupu-kupu');
INSERT INTO "words" VALUES (1065,'벌','Beol','Lebah');
INSERT INTO "words" VALUES (1066,'모기','Mogi','Nyamuk');
INSERT INTO "words" VALUES (1067,'파리','Pari','Lalat');
INSERT INTO "words" VALUES (1068,'거미','Geomi','Laba-laba');
INSERT INTO "words" VALUES (1069,'개미','Gaemi','Semut');
INSERT INTO "words" VALUES (1070,'쥐','Jwi','Tikus');
INSERT INTO "words" VALUES (1071,'뱀','Baem','Ular');
INSERT INTO "words" VALUES (1072,'용','Yong','Naga');
INSERT INTO "words" VALUES (1073,'공룡','Gongnyong','Dinosaurus');
INSERT INTO "words" VALUES (1074,'애완동물','Aewandongmul','Hewan peliharaan');
INSERT INTO "words" VALUES (1075,'가구','Gagu','Mebel');
INSERT INTO "words" VALUES (1076,'소파','Sopa','Sofa');
INSERT INTO "words" VALUES (1077,'옷장','Otjang','Lemari pakaian');
INSERT INTO "words" VALUES (1078,'서랍','Seorap','Laci');
INSERT INTO "words" VALUES (1079,'선반','Seonban','Rak');
INSERT INTO "words" VALUES (1080,'거울','Geoul','Cermin');
INSERT INTO "words" VALUES (1081,'카펫','Kapet','Karpet');
INSERT INTO "words" VALUES (1082,'커튼','Keoteun','Gorden');
INSERT INTO "words" VALUES (1083,'조명','Jomyeong','Pencahayaan');
INSERT INTO "words" VALUES (1084,'전구','Jeon-gu','Bohlam');
INSERT INTO "words" VALUES (1085,'스위치','Seuwichi','Saklar');
INSERT INTO "words" VALUES (1086,'콘센트','Konsenteu','Stopkontak');
INSERT INTO "words" VALUES (1087,'가전제품','Gajeonjepum','Peralatan elektronik');
INSERT INTO "words" VALUES (1088,'냉장고','Naengjanggo','Kulkas');
INSERT INTO "words" VALUES (1089,'세탁기','Setakgi','Mesin cuci');
INSERT INTO "words" VALUES (1090,'에어컨','E-eokeon','AC');
INSERT INTO "words" VALUES (1091,'선풍기','Seonpung-gi','Kipas angin');
INSERT INTO "words" VALUES (1092,'청소기','Cheongsogi','Penyedot debu');
INSERT INTO "words" VALUES (1093,'전자레인지','Jeonjareinji','Microwave');
INSERT INTO "words" VALUES (1094,'밥솥','Bapsot','Penanak nasi');
INSERT INTO "words" VALUES (1095,'주방','Jubang','Dapur');
INSERT INTO "words" VALUES (1096,'그릇','Geureut','Mangkuk');
INSERT INTO "words" VALUES (1097,'접시','Jeopsi','Piring');
INSERT INTO "words" VALUES (1098,'컵','Keop','Cangkir');
INSERT INTO "words" VALUES (1099,'숟가락','Sutgarak','Sendok');
INSERT INTO "words" VALUES (1100,'젓가락','Jeotgarak','Sumpit');
INSERT INTO "words" VALUES (1101,'칼','Kal','Pisau');
INSERT INTO "words" VALUES (1102,'냄비','Naembi','Panci');
INSERT INTO "words" VALUES (1103,'프라이팬','Peuraipaen','Wajan');
INSERT INTO "words" VALUES (1104,'욕실','Yoksil','Kamar mandi');
INSERT INTO "words" VALUES (1105,'샤워기','Syawogi','Pancuran');
INSERT INTO "words" VALUES (1106,'욕조','Yokjo','Bak mandi');
INSERT INTO "words" VALUES (1107,'세면대','Semyeondae','Wastafel');
INSERT INTO "words" VALUES (1108,'비누','Binu','Sabun');
INSERT INTO "words" VALUES (1109,'샴푸','Syampu','Sampo');
INSERT INTO "words" VALUES (1110,'칫솔','Chitsol','Sikat gigi');
INSERT INTO "words" VALUES (1111,'치약','Chiyak','Pasta gigi');
INSERT INTO "words" VALUES (1112,'수건','Sugeon','Handuk');
INSERT INTO "words" VALUES (1113,'의류','Uiryu','Pakaian');
INSERT INTO "words" VALUES (1114,'티셔츠','Tisyeocheu','Kaos');
INSERT INTO "words" VALUES (1115,'바지','Baji','Celana');
INSERT INTO "words" VALUES (1116,'치마','Chima','Rok');
INSERT INTO "words" VALUES (1117,'원피스','Wonpiseu','Gaun');
INSERT INTO "words" VALUES (1118,'셔츠','Syeocheu','Kemeja');
INSERT INTO "words" VALUES (1119,'재킷','Jaekit','Jaket');
INSERT INTO "words" VALUES (1120,'코트','Koteu','Mantel');
INSERT INTO "words" VALUES (1121,'스웨터','Seuweteo','Sweater');
INSERT INTO "words" VALUES (1122,'양말','Yangmal','Kaus kaki');
INSERT INTO "words" VALUES (1123,'속옷','Sogot','Pakaian dalam');
INSERT INTO "words" VALUES (1124,'잠옷','Jamot','Piyama');
INSERT INTO "words" VALUES (1125,'수영복','Suyeongbok','Pakaian renang');
INSERT INTO "words" VALUES (1126,'액세서리','Akseseori','Aksesoris');
INSERT INTO "words" VALUES (1127,'귀걸이','Gwigeori','Anting');
INSERT INTO "words" VALUES (1128,'목걸이','Mokgeori','Kalung');
INSERT INTO "words" VALUES (1129,'반지','Banji','Cincin');
INSERT INTO "words" VALUES (1130,'팔찌','Paljji','Gelang');
INSERT INTO "words" VALUES (1131,'벨트','Belteu','Ikat pinggang');
INSERT INTO "words" VALUES (1132,'스카프','Seukapeu','Syal');
INSERT INTO "words" VALUES (1133,'장갑','Jang-gap','Sarung tangan');
INSERT INTO "words" VALUES (1134,'운동화','Undonghwa','Sepatu olahraga');
INSERT INTO "words" VALUES (1135,'구두','Gudu','Sepatu formal');
INSERT INTO "words" VALUES (1136,'부츠','Bucheu','Sepatu bot');
INSERT INTO "words" VALUES (1137,'샌들','Saendeul','Sandal');
INSERT INTO "words" VALUES (1138,'슬리퍼','Seullipeo','Sandal rumah');
INSERT INTO "words" VALUES (1139,'건물','Geonmul','Bangunan');
INSERT INTO "words" VALUES (1140,'다리','Dari','Jembatan');
INSERT INTO "words" VALUES (1141,'도로','Doro','Jalan raya');
INSERT INTO "words" VALUES (1142,'골목','Golmok','Gang');
INSERT INTO "words" VALUES (1143,'횡단보도','Hoengdanbodo','Zebra cross');
INSERT INTO "words" VALUES (1144,'신호등','Sinhodeung','Lampu lalu lintas');
INSERT INTO "words" VALUES (1145,'간판','Ganpan','Papan nama');
INSERT INTO "words" VALUES (1146,'우산','Usan','Payung');
INSERT INTO "words" VALUES (1147,'열쇠','Yeolsoe','Kunci');
INSERT INTO "words" VALUES (1148,'자물쇠','Jamulsoe','Gembok');
INSERT INTO "words" VALUES (1149,'계단','Gyedan','Tangga');
INSERT INTO "words" VALUES (1150,'엘리베이터','Ellibeiteo','Lift');
INSERT INTO "words" VALUES (1151,'에스컬레이터','Eseukeolleiteo','Eskalator');
INSERT INTO "words" VALUES (1152,'지붕','Jibung','Atap');
INSERT INTO "words" VALUES (1153,'벽','Byeok','Dinding');
INSERT INTO "words" VALUES (1154,'바닥','Badak','Lantai');
INSERT INTO "words" VALUES (1155,'천장','Cheonjang','Langit-langit');
INSERT INTO "words" VALUES (1156,'기둥','Gidung','Tiang');
INSERT INTO "words" VALUES (1157,'장난감','Jangnan-gam','Mainan');
INSERT INTO "words" VALUES (1158,'인형','Inhyeong','Boneka');
INSERT INTO "words" VALUES (1159,'공','Gong','Bola');
INSERT INTO "words" VALUES (1160,'카드','Kadeu','Kartu');
INSERT INTO "words" VALUES (1161,'선','Seon','Garis');
INSERT INTO "words" VALUES (1162,'점','Jeom','Titik');
INSERT INTO "words" VALUES (1163,'모양','Moyang','Bentuk');
INSERT INTO "words" VALUES (1164,'동그라미','Dong-geurami','Lingkaran');
INSERT INTO "words" VALUES (1165,'세모','Semo','Segitiga');
INSERT INTO "words" VALUES (1166,'네모','Nemo','Persegi');
INSERT INTO "words" VALUES (1167,'소포','Sopo','Paket');
INSERT INTO "words" VALUES (1168,'상자','Sangja','Kotak');
COMMIT;
